const SET_SEARCH_LIST = 'SET_SEARCH_LIST';
const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
const SET_MOST_POPULAR_VIDEO_LIST = 'SET_MOST_POPULAR_VIDEO_LIST';
const SET_SEARCH_LIST_IN_VIDEO = 'SET_SEARCH_LIST_IN_VIDEO';

export { SET_SEARCH_LIST, SET_CATEGORY_LIST, SET_MOST_POPULAR_VIDEO_LIST, SET_SEARCH_LIST_IN_VIDEO };
