const SET_SEARCH_LIST = 'SET_SEARCH_LIST';
const SET_RECOMMENDED_LIST = 'SET_RECOMMENDED_LIST';
const SET_MOST_POPULAR_VIDEO_LIST = 'SET_MOST_POPULAR_VIDEO_LIST';
const SET_SEARCH_LIST_IN_VIDEO = 'SET_SEARCH_LIST_IN_VIDEO';
const SET_COMMENT_LIST = 'SET_COMMENT_LIST';

export {
  SET_SEARCH_LIST,
  SET_RECOMMENDED_LIST,
  SET_MOST_POPULAR_VIDEO_LIST,
  SET_SEARCH_LIST_IN_VIDEO,
  SET_COMMENT_LIST,
};
